spring:
  datasource:
    url: jdbc:mysql://localhost:3306/steam
    username: root
    password: 1234

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql

  security:
    user:
      name: admin
      password: 1234

  servlet:
    multipart:
      max-file-size: 10MB

cloud:
  aws:
    stack:
      auto: false
    s3:
        bucket: steam-bucket
        region:
            static: ap-northeast-2
        credentials:
            accessKey: accessKey
            secretKey: secretKey